### ISSUE TITLE
Add reversal

### ISSUE THREAD

**Issue by mhulse** [mhulse/waffle#2]
Once I get the core functionality working, add:

``` css
[wg-row ~= "reverse"] { flex-direction: row-reverse; }

[wg-row ~= "column"] { flex-direction: column; }
[wg-row ~= "column"][wg-row ~= "reverse"] { flex-direction: column-reverse; }
```
